### 
POST http://localhost:3333/goals HTTP/1.1
content-type: application/json

{
    "title": "Não usar o celular a noite",
    "desiredWeeklyFrequency": 3
}

### 
get http://localhost:3333/pending-goals HTTP/1.1

### 
post http://localhost:3333/completions HTTP/1.1
content-type: application/json

{
    "goalId": "fwl6frkzmxyptwqfryu63350"
}
